num1 = int(input("enter the first number:" ))
num2 = int(input("enter the second number:" ))
num3 = int(input("enter the third number:" ))
print("before swapping:" )
print(num1, num2, num3)
print("after swapping:" )
print(num2,num3,num1)
